st_name1="DANIYAL";
m1=100;
m2=50;
m3=70;
st_name2="MADHAN";
k1=90;
k2=50;
k3=80;
st_name3="BAVITHRAN";
v1=60;
v2=50;
v3=70;
st_name4="ALWIN";
b1=70;
b2=50;
b3=80;
console.log("STUDENT NAME:",st_name1);
console.log("STUDENT MARKS:",m1,",",m2,",",m3);
console.log("STUDENT MARKS TOTAL:",m1+m2+m3);
console.log("STUDENT MARK AVERAGE:",(m1+m2+m3)/3);
console.log("STUDENT NAME:",st_name2);
console.log("STUDENT MARKS:",k1,",",k2,",",k3);
console.log("STUDENT MARKS TOTAL:",k1+k2+k3);
console.log("STUDENT MARKES AVERAGE:",(k1+k2+k3)/3);
console.log("STUDENT NAME:",st_name3);
console.log("STUDENT MARKS:",v1,",",v2,",",v3);
console.log("STUDENT MARKS TOTAL:",v1+v2+v3);
console.log("STUDENT MARKS AVERAGE:",(v1+v2+v3)/3);
console.log("STUDENT NAME:",st_name4);
console.log("STUDENT MARKS:",b1,",",b2,",",b3);
console.log("STUDENT MARKS TOTAL:",b1+b2+b3);
console.log("STUDENT MARKS AVERAGE:",(b1+b2+b3)/3);